import discord
import aiofiles
import os
from datetime import datetime
from typing import List, Tuple
from models.ticket import Ticket
from config.config import config
import logging

logger = logging.getLogger(__name__)

class TranscriptService:
    def __init__(self, bot):
        self.bot = bot
    
    async def generate_transcript(self, channel: discord.TextChannel, ticket: Ticket) -> str:
        """Generate an HTML transcript of the ticket channel and return file path."""
        messages = []
        async for message in channel.history(limit=500, oldest_first=True):
            messages.append(message)
        
        # Create HTML content
        html = self._build_html(messages, channel, ticket)
        
        # Save to temp file
        filename = f"transcript_{ticket.ticket_id}_{int(datetime.utcnow().timestamp())}.html"
        filepath = f"/tmp/{filename}"
        
        async with aiofiles.open(filepath, "w", encoding="utf-8") as f:
            await f.write(html)
        
        return filepath
    
    def _build_html(self, messages: List[discord.Message], channel: discord.TextChannel, ticket: Ticket) -> str:
        """Build HTML content from messages."""
        # Simple HTML template – can be expanded with CSS
        html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Transcript - Ticket {ticket.ticket_id}</title>
    <style>
        body {{ font-family: Arial, sans-serif; background: #f0f0f0; padding: 20px; }}
        .container {{ max-width: 800px; margin: auto; background: white; border-radius: 10px; padding: 20px; box-shadow: 0 0 10px rgba(0,0,0,0.1); }}
        .message {{ margin-bottom: 15px; padding: 10px; border-left: 3px solid #7289da; background: #f9f9f9; }}
        .author {{ font-weight: bold; color: #7289da; }}
        .timestamp {{ font-size: 0.8em; color: gray; margin-left: 10px; }}
        .content {{ margin-top: 5px; }}
        hr {{ margin: 20px 0; }}
        .footer {{ text-align: center; font-size: 0.8em; color: gray; margin-top: 20px; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Transcript for Ticket #{ticket.ticket_id}</h1>
        <p><strong>User:</strong> <@{ticket.user_id}> (ID: {ticket.user_id})</p>
        <p><strong>Channel:</strong> #{channel.name}</p>
        <p><strong>Created:</strong> {ticket.created_at.strftime('%Y-%m-%d %H:%M:%S UTC')}</p>
        <p><strong>Closed:</strong> {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}</p>
        <hr>
"""
        for msg in messages:
            timestamp = msg.created_at.strftime('%Y-%m-%d %H:%M:%S')
            author_name = msg.author.display_name if hasattr(msg.author, 'display_name') else str(msg.author)
            content = msg.clean_content or "*No text content*"
            html += f"""
        <div class="message">
            <div class="author">{author_name} <span class="timestamp">({timestamp})</span></div>
            <div class="content">{content}</div>
        </div>
"""
        html += """
        <hr>
        <div class="footer">Generated by ModMail Bot</div>
    </div>
</body>
</html>"""
        return html
    
    async def send_transcript(self, guild_id: int, ticket: Ticket, channel: discord.TextChannel, filepath: str) -> str:
        """Send transcript to configured transcripts channel and return message URL."""
        from services.guild_config_service import GuildConfigService
        config_service = GuildConfigService(self.bot.db)
        guild_config = await config_service.get_config(guild_id)
        
        if not guild_config.transcripts_channel_id:
            logger.warning(f"No transcripts channel set for guild {guild_id}")
            return None
        
        transcript_channel = self.bot.get_channel(guild_config.transcripts_channel_id)
        if not transcript_channel:
            try:
                transcript_channel = await self.bot.fetch_channel(guild_config.transcripts_channel_id)
            except:
                logger.error(f"Could not find transcripts channel {guild_config.transcripts_channel_id}")
                return None
        
        embed = discord.Embed(
            title="📄 Ticket Transcript",
            description=f"**Ticket ID:** {ticket.ticket_id}\n**User:** <@{ticket.user_id}>\n**Channel:** <#{channel.id}>",
            color=discord.Color.blue(),
            timestamp=datetime.utcnow()
        )
        
        file = discord.File(filepath, filename=f"transcript_{ticket.ticket_id}.html")
        message = await transcript_channel.send(embed=embed, file=file)
        
        # Clean up temp file
        try:
            os.remove(filepath)
        except:
            pass
        
        return message.jump_url
