import discord
import aiofiles
import os
from datetime import datetime
from typing import List, Tuple
from models.ticket import Ticket
from config.config import config
import logging

logger = logging.getLogger(__name__)

class TranscriptService:
    def __init__(self, bot):
        self.bot = bot
    
    async def generate_transcript(self, channel: discord.TextChannel, ticket: Ticket) -> str:
        """Generate an HTML transcript of the ticket channel and return file path."""
        messages = []
        async for message in channel.history(limit=500, oldest_first=True):
            messages.append(message)
        
        html = self._build_html(messages, channel, ticket)
        
        filename = f"transcript_{ticket.ticket_id}_{int(datetime.utcnow().timestamp())}.html"
        filepath = f"/tmp/{filename}"
        
        async with aiofiles.open(filepath, "w", encoding="utf-8") as f:
            await f.write(html)
        
        return filepath
    
    def _build_html(self, messages: List[discord.Message], channel: discord.TextChannel, ticket: Ticket) -> str:
        """Build enhanced HTML content from messages including attachments."""
        html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Transcript - Ticket {ticket.ticket_id}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background: #36393f; padding: 20px; margin: 0; }}
        .container {{ max-width: 1000px; margin: 0 auto; background: #2f3136; border-radius: 8px; padding: 20px; box-shadow: 0 2px 10px rgba(0,0,0,0.2); }}
        .header {{ border-bottom: 1px solid #202225; padding-bottom: 10px; margin-bottom: 20px; }}
        .header h1 {{ color: #fff; margin: 0; }}
        .header p {{ color: #b9bbbe; margin: 5px 0; }}
        .message {{ margin-bottom: 15px; padding: 10px; background: #40444b; border-radius: 8px; }}
        .message:hover {{ background: #4f545c; }}
        .author {{ font-weight: bold; color: #7289da; display: inline-block; }}
        .timestamp {{ font-size: 0.75em; color: #72767d; margin-left: 10px; }}
        .content {{ margin-top: 8px; color: #dcddde; white-space: pre-wrap; word-wrap: break-word; }}
        .attachment {{ margin-top: 8px; padding: 8px; background: #2f3136; border-radius: 4px; border-left: 3px solid #7289da; }}
        .attachment a {{ color: #00b0f4; text-decoration: none; }}
        .attachment a:hover {{ text-decoration: underline; }}
        hr {{ border: none; border-top: 1px solid #202225; margin: 20px 0; }}
        .footer {{ text-align: center; font-size: 0.8em; color: #72767d; margin-top: 20px; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Transcript for Ticket #{ticket.ticket_id}</h1>
            <p><strong>User:</strong> {ticket.user_id} (ID: {ticket.user_id})</p>
            <p><strong>Channel:</strong> #{channel.name}</p>
            <p><strong>Created:</strong> {ticket.created_at.strftime('%Y-%m-%d %H:%M:%S UTC') if ticket.created_at else 'Unknown'}</p>
            <p><strong>Closed:</strong> {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}</p>
        </div>
        <hr>
"""
        for msg in messages:
            timestamp = msg.created_at.strftime('%Y-%m-%d %H:%M:%S')
            author_name = msg.author.display_name if hasattr(msg.author, 'display_name') else str(msg.author)
            content = msg.clean_content or "*No text content*"
            html += f"""
        <div class="message">
            <div class="author">{author_name}</div>
            <div class="timestamp">({timestamp})</div>
            <div class="content">{content}</div>
"""
            # Add attachments
            if msg.attachments:
                for attachment in msg.attachments:
                    html += f"""
            <div class="attachment">
                📎 <a href="{attachment.url}">{attachment.filename}</a> ({attachment.size // 1024} KB)
            </div>
"""
            # Add embeds (simplified)
            if msg.embeds:
                for embed in msg.embeds:
                    html += f"""
            <div class="attachment">
                🔗 Embed: {embed.title or 'No title'} - {embed.url or ''}
            </div>
"""
            html += """
        </div>
"""
        html += """
        <hr>
        <div class="footer">Generated by ModMail Bot • Transcript includes up to 500 messages</div>
    </div>
</body>
</html>"""
        return html
    
    async def send_transcript(self, guild_id: int, ticket: Ticket, channel: discord.TextChannel, filepath: str) -> str:
        """Send transcript to configured transcripts channel and return message URL."""
        from services.guild_config_service import GuildConfigService
        config_service = GuildConfigService(self.bot.db)
        guild_config = await config_service.get_config(guild_id)
        
        if not guild_config.transcripts_channel_id:
            logger.warning(f"No transcripts channel set for guild {guild_id}")
            return None
        
        transcript_channel = self.bot.get_channel(guild_config.transcripts_channel_id)
        if not transcript_channel:
            try:
                transcript_channel = await self.bot.fetch_channel(guild_config.transcripts_channel_id)
            except:
                logger.error(f"Could not find transcripts channel {guild_config.transcripts_channel_id}")
                return None
        
        embed = discord.Embed(
            title="📄 Ticket Transcript",
            description=f"**Ticket ID:** {ticket.ticket_id}\n**User:** <@{ticket.user_id}>\n**Channel:** <#{channel.id}>",
            color=discord.Color.blue(),
            timestamp=datetime.utcnow()
        )
        
        file = discord.File(filepath, filename=f"transcript_{ticket.ticket_id}.html")
        message = await transcript_channel.send(embed=embed, file=file)
        
        try:
            os.remove(filepath)
        except:
            pass
        
        return message.jump_url
